# -*- coding: utf-8 -*-
"""AI-Based-Peak-Hour-Electricity-Prediction-Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDzB6usbvPq0D86BiM1wPFnWnqfcKnhY
"""

from google.colab import files
files.upload()

!pip install pandas scikit-learn plotly

import pandas as pd

df = pd.read_csv("/content/electricity_data.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])
df["hour"] = df["timestamp"].dt.hour
df["day"] = df["timestamp"].dt.date

df.head()

from sklearn.linear_model import LinearRegression

df["smoothed_consumption"] = df["consumption_kwh"].rolling(window=3).mean()
df = df.dropna()

X = df[["hour"]]
y = df["smoothed_consumption"]

model = LinearRegression()
model.fit(X, y)

future_hours = pd.DataFrame({"hour": [18, 19, 20, 21, 22]})
predicted = model.predict(future_hours)

for h, val in zip(future_hours["hour"], predicted):
    print(f"Hour {h}:00 → {val:.2f} kWh")

import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=df["timestamp"],
    y=df["consumption_kwh"],
    mode="lines",
    name="Actual Consumption"
))

fig.add_trace(go.Scatter(
    x=df["timestamp"],
    y=df["smoothed_consumption"],
    mode="lines",
    name="Smoothed Consumption"
))

fig.show()