# -*- coding: utf-8 -*-
"""Week5HackOweek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z1e7tpMfz3hqS74BeWe_qQgrA1t3Qvtt
"""

# =============================================================================
# PROJECT 5: HVAC OPTIMIZATION IN LABS
# Requirements: Decision Tree + Heatmap Dashboard + Real-time Simulation
# =============================================================================

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
from IPython.display import clear_output
import time

# 1. SETUP & DATA GENERATION
print("🚀 Initializing Project 5...")
np.random.seed(42)
temp = np.random.uniform(18, 35, 500)      # Temp in Celsius
occupancy = np.random.randint(0, 60, 500) # Number of students students

df_hvac = pd.DataFrame({'temperature': temp, 'occupancy': occupancy})

# Decision Logic for HVAC State
def label_hvac(row):
    if row['occupancy'] > 40 or (row['temperature'] > 28 and row['occupancy'] > 10):
        return 2 # High Cooling
    elif row['temperature'] > 22 and row['occupancy'] > 5:
        return 1 # Low Cooling
    else:
        return 0 # HVAC Off

df_hvac['hvac_state'] = df_hvac.apply(label_hvac, axis=1)
df_hvac.to_csv('hvac_optimization_data.csv', index=False)
print("✅ Dataset generated: hvac_optimization_data.csv")

# 2. MODEL TRAINING
X = df_hvac[['temperature', 'occupancy']]
y = df_hvac['hvac_state']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = DecisionTreeClassifier(max_depth=3, random_state=42)
clf.fit(X_train, y_train)
print(f"🎯 Decision Tree Model Trained. Accuracy: {clf.score(X_test, y_test):.2%}")

# 3. VISUALIZATION: DECISION LOGIC TREE
plt.figure(figsize=(12,6))
plot_tree(clf, feature_names=['Temp', 'Occupancy'],
          class_names=['Off', 'Low', 'High'], filled=True, rounded=True)
plt.title("Lab HVAC Optimization Decision Logic")
plt.show()

# 4. DASHBOARD: ZONE-WISE PREDICTION HEATMAP
print("\n📊 Generating HVAC Prediction Heatmap...")
t_range = np.linspace(18, 35, 30)
o_range = np.linspace(0, 60, 30)
tt, oo = np.meshgrid(t_range, o_range)

grid_preds = clf.predict(np.c_[tt.ravel(), oo.ravel()])
grid_preds = grid_preds.reshape(tt.shape)

fig = go.Figure(data=go.Heatmap(
    z=grid_preds,
    x=t_range,
    y=o_range,
    colorscale=[[0, '#3498db'], [0.5, '#f1c40f'], [1, '#e74c3c']],
    colorbar=dict(title='HVAC State', tickvals=[0, 1, 2], ticktext=['OFF', 'LOW', 'HIGH'])
))

fig.update_layout(
    title='Interactive HVAC Optimization Map (Temperature vs Occupancy)',
    xaxis_title='Temperature (°C)',
    yaxis_title='Student Occupancy',
    height=500
)
fig.show()

# 5. REAL-TIME SENSOR SIMULATION
print("\n🔌 Starting Real-Time Sensor Stream Simulation...")
try:
    for i in range(5):
        curr_temp = np.random.uniform(20, 33)
        curr_occ = np.random.randint(2, 55)

        # Predict state
        res = clf.predict([[curr_temp, curr_occ]])[0]
        status = ['OFF', 'LOW COOLING', 'HIGH COOLING'][res]

        print(f"[Sensor {i+1}] Lab Condition: {curr_temp:.1f}°C | Students: {curr_occ} >> Action: {status}")
        time.sleep(1)
    print("\n✅ Simulation Complete.")
except KeyboardInterrupt:
    print("\nStopped.")