# -*- coding: utf-8 -*-
"""Event-Aware Library Energy Forecasting During Examination Periods Using Exponential Smoothing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yRKDV0aE0C-JUFo4ZDS3LgRSSv_mxc51
"""

!pip install pandas numpy matplotlib statsmodels plotly

!mkdir data

# Commented out IPython magic to ensure Python compatibility.
# %%writefile generate_library_data.py
# import pandas as pd
# import numpy as np
# 
# dates = pd.date_range("2024-08-01", periods=120)
# 
# energy = []
# event = []
# 
# for d in dates:
#     if d.month == 11:  # Exam month
#         energy.append(np.random.uniform(450, 650))
#         event.append("Exam")
#     else:
#         energy.append(np.random.uniform(200, 350))
#         event.append("Normal")
# 
# df = pd.DataFrame({
#     "date": dates,
#     "energy_kwh": energy,
#     "event_type": event
# })
# 
# df.to_csv("data/library_energy.csv", index=False)
# print("Library energy data generated.")
#

!python generate_library_data.py

!ls data

import pandas as pd
import matplotlib.pyplot as plt
from statsmodels.tsa.holtwinters import ExponentialSmoothing

df = pd.read_csv("data/library_energy.csv")
df["date"] = pd.to_datetime(df["date"])
df.set_index("date", inplace=True)

model = ExponentialSmoothing(
    df["energy_kwh"],
    trend="add",
    seasonal=None
)

fit = model.fit()
forecast = fit.forecast(15)

print("Semester-end energy forecast:")
print(forecast)

plt.figure(figsize=(10,4))
plt.plot(df.index, df["energy_kwh"], label="Historical Usage")
plt.plot(forecast.index, forecast, label="Forecast", linestyle="--")
plt.xlabel("Date")
plt.ylabel("Energy (kWh)")
plt.title("Library Energy Forecast During Exams")
plt.legend()
plt.show()

import plotly.graph_objects as go

latest_forecast = forecast.mean()

fig = go.Figure(go.Indicator(
    mode="gauge+number",
    value=latest_forecast,
    title={'text': "Predicted Library Energy Usage (kWh)"},
    gauge={
        'axis': {'range': [0, 700]},
        'steps': [
            {'range': [0, 300], 'color': "lightgreen"},
            {'range': [300, 500], 'color': "yellow"},
            {'range': [500, 700], 'color': "red"}
        ]
    }
))

fig.show()

