# -*- coding: utf-8 -*-
"""Wi-Fi Based Classroom Electricity Consumption Forecasting Using Time Series Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WpTBGNLL42-GIS7SRrtB3ClDQETzrdRT
"""

!pip install pandas numpy matplotlib statsmodels plotly

!mkdir data

# Commented out IPython magic to ensure Python compatibility.
# %%writefile generate_data.py
# import pandas as pd
# import numpy as np
# from datetime import datetime, timedelta
# 
# start_time = datetime(2025, 1, 1, 8, 0)
# num_records = 120  # 5-min intervals for 10 hours
# 
# timestamps = []
# occupancy = []
# current_time = start_time
# 
# for i in range(num_records):
#     hour = current_time.hour
#     if 9 <= hour <= 16:
#         people = np.random.randint(20, 50)
#     else:
#         people = np.random.randint(0, 5)
# 
#     timestamps.append(current_time)
#     occupancy.append(people)
#     current_time += timedelta(minutes=5)
# 
# df = pd.DataFrame({
#     "timestamp": timestamps,
#     "connected_devices": occupancy
# })
# 
# df.to_csv("data/wifi_occupancy.csv", index=False)
# print("Wi-Fi occupancy data generated.")
#

!python generate_data.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile model.py
# import pandas as pd
# import matplotlib.pyplot as plt
# from statsmodels.tsa.arima.model import ARIMA
# 
# df = pd.read_csv("data/wifi_occupancy.csv")
# df["timestamp"] = pd.to_datetime(df["timestamp"])
# df.set_index("timestamp", inplace=True)
# 
# BASE_LOAD = 2.0
# POWER_PER_DEVICE = 0.15
# 
# df["electricity_kW"] = BASE_LOAD + (df["connected_devices"] * POWER_PER_DEVICE)
# 
# df.to_csv("data/electricity_usage.csv")
# 
# plt.figure(figsize=(10,4))
# plt.plot(df.index, df["electricity_kW"], label="Electricity Usage (kW)")
# plt.legend()
# plt.xlabel("Time")
# plt.ylabel("kW")
# plt.title("Electricity Usage Over Time")
# plt.show()
# 
# model = ARIMA(df["electricity_kW"], order=(1,1,1))
# model_fit = model.fit()
# 
# forecast = model_fit.get_forecast(steps=12)
# print("Next 1 hour forecast:")
# print(forecast.predicted_mean)
#

!python model.py