# -*- coding: utf-8 -*-
"""Week4HackOweek.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QkZA_bZ1xMiT9zyCR80acW_wcdmnqja
"""

!pip install pandas numpy scikit-learn matplotlib plotly websockets asyncio ipywidgets -q

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from IPython.display import display, clear_output
import time
import pickle
import json
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully!")

def generate_cafeteria_data(n_days=90):
    np.random.seed(42)
    data = []
    start_date = datetime(2025, 9, 1)
    weather_conditions = ['sunny', 'cloudy', 'rainy']

    for day in range(n_days):
        current_date = start_date + timedelta(days=day)
        day_of_week = current_date.weekday()
        is_weekend = day_of_week >= 5
        daily_temp_base = 25 + 10 * np.sin(2 * np.pi * day / 90)
        daily_weather = np.random.choice(weather_conditions, p=[0.5, 0.3, 0.2])

        for hour in range(7, 20):
            temp = daily_temp_base + 5 * np.sin(np.pi * (hour - 6) / 12) + np.random.normal(0, 2)
            base_load = 50 if is_weekend else 150
            is_lunch_hour = 1 if 11 <= hour <= 14 else 0
            lunch_surge = 200 if is_lunch_hour else 0
            breakfast_surge = 80 if 7 <= hour <= 9 else 0
            dinner_surge = 100 if 17 <= hour <= 19 else 0

            weather_impact = {'sunny': -20, 'cloudy': 10, 'rainy': 50}
            temp_impact = 40 if temp > 35 else (30 if temp < 15 else 0)

            load = (base_load + lunch_surge + breakfast_surge + dinner_surge +
                   weather_impact[daily_weather] + temp_impact + np.random.normal(0, 20))

            data.append({
                'datetime': current_date.replace(hour=hour),
                'hour': hour,
                'day_of_week': day_of_week,
                'is_weekend': int(is_weekend),
                'is_lunch_hour': is_lunch_hour,
                'temperature': round(temp, 1),
                'weather': daily_weather,
                'customer_load': max(10, int(load))
            })
    return pd.DataFrame(data)

df = generate_cafeteria_data()
df.to_csv('cafeteria_load_data.csv', index=False)
print(f"📈 Generated {len(df)} records. Data saved to 'cafeteria_load_data.csv'")

def prepare_features(data_df):
    df_f = data_df.copy()
    weather_dummies = pd.get_dummies(df_f['weather'], prefix='weather')
    df_f = pd.concat([df_f, weather_dummies], axis=1)
    df_f['hour_sin'] = np.sin(2 * np.pi * df_f['hour'] / 24)
    df_f['hour_cos'] = np.cos(2 * np.pi * df_f['hour'] / 24)
    df_f['temp_squared'] = df_f['temperature'] ** 2
    df_f['is_hot'] = (df_f['temperature'] > 35).astype(int)
    df_f['is_cold'] = (df_f['temperature'] < 15).astype(int)
    return df_f

df_processed = prepare_features(df)
feature_cols = ['hour', 'day_of_week', 'is_weekend', 'is_lunch_hour', 'temperature',
                'temp_squared', 'is_hot', 'is_cold', 'hour_sin', 'hour_cos',
                'weather_sunny', 'weather_cloudy', 'weather_rainy']

X = df_processed[feature_cols]
y = df_processed['customer_load']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression().fit(X_train, y_train)
print(f"🎯 Model Trained! R2 Score: {r2_score(y_test, model.predict(X_test)):.4f}")

class RealTimePredictor:
    def __init__(self, model, features):
        self.model, self.features = model, features
        self.actuals, self.preds, self.temps = [], [], []

    def simulate(self):
        hour = np.random.randint(7, 20)
        temp = 25 + np.random.normal(0, 8)
        weather = np.random.choice(['sunny', 'cloudy', 'rainy'])
        is_lunch = 1 if 11 <= hour <= 14 else 0

        # Mock actual load
        act = (150 + (200 if is_lunch else 0) + np.random.normal(0, 30))

        # Prepare for prediction
        feat_dict = {col: 0 for col in self.features}
        feat_dict.update({'hour': hour, 'temperature': temp, 'is_lunch_hour': is_lunch,
                          'temp_squared': temp**2, f'weather_{weather}': 1})
        pred = self.model.predict(pd.DataFrame([feat_dict])[self.features])[0]

        self.actuals.append(act); self.preds.append(pred); self.temps.append(temp)

predictor = RealTimePredictor(model, feature_cols)

for i in range(15):
    predictor.simulate()
    clear_output(wait=True)
    fig = make_subplots(rows=1, cols=1)
    fig.add_trace(go.Scatter(y=predictor.actuals, name="Actual Load", line=dict(color='blue')))
    fig.add_trace(go.Scatter(y=predictor.preds, name="Predicted Load", line=dict(color='red', dash='dash')))
    fig.update_layout(title=f"Update #{i+1}: Real-Time Cafeteria Surge Prediction", height=400)
    fig.show()
    time.sleep(0.5)

